spring.application.name=backend

datashare.storage.endpoint=${GARAGE_S3_ENDPOINT:http://localhost:3900}
datashare.storage.region=garage
datashare.storage.bucket=${GARAGE_BUCKET}
datashare.storage.access-key=${GARAGE_ACCESS_KEY}
datashare.storage.secret-key=${GARAGE_SECRET_KEY}
